# Scraping Zara.com
Collecte des données produits via Selenium (Firefox headless) + regex sur le HTML rendu.

**Variables collectées :** nom, url, categorie, couleur, matiere, collection, pays, prix, promo, reference

## 0. Installation des dépendances

In [ ]:
# À lancer une seule fois si les packages ne sont pas installés
# !pip install selenium webdriver-manager beautifulsoup4 pandas

## 1. Imports & Configuration

In [2]:
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.common.exceptions import WebDriverException
from webdriver_manager.firefox import GeckoDriverManager
import re
import time
import pandas as pd
from bs4 import BeautifulSoup #Pour extraire et manipuler des données HTML

In [3]:
# Colonnes du DataFrame final
VARIABLES = ["nom", "url", "couleur", "matiere", "prix"]

In [4]:
# URLs de départ — pages liste de produits par collection
# (changer l'URL pour cibler une autre catégorie ou promotion)
URLS_LISTES = {
    "femme":   "https://www.zara.com/fr/fr/femme-nouveau-l1180.html",
    "homme":   "https://www.zara.com/fr/fr/homme-nouveau-l711.html",
    "fille": "https://www.zara.com/fr/fr/enfants-fille-nouveau-l391.html",
    "garçon": "https://www.zara.com/fr/fr/enfants-garcon-nouveau-l228.html"
}

PAYS = "France"

## 2. Lancement du navigateur (Firefox headless)

In [5]:
# headless=True = pas de fenêtre visible (recommandé pour du scraping en batch)
# Mettre headless=False si tu veux voir le navigateur s'ouvrir
HEADLESS = True

options = Options()
if HEADLESS:
    options.add_argument("--headless")

driver = webdriver.Firefox(
    service=Service(GeckoDriverManager().install()),
    options=options
)
print("Navigateur lancé.")

Navigateur lancé.

## 3. Extraction des URLs produits depuis une page liste

In [6]:
def get_product_urls(driver, listing_url, pause=8):
    """
    Charge une page liste Zara et extrait toutes les URLs produit.
    Les URLs produit Zara contiennent '-p' suivi de chiffres.
    """
    driver.get(listing_url)
    time.sleep(pause)

    # Scroll pour charger les produits en lazy-loading
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight / 2);")
    time.sleep(2)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)

    links = driver.find_elements(By.TAG_NAME, "a")
    urls = set()
    for link in links:
        href = link.get_attribute("href")
        if href and "zara.com/fr/fr/" in href and re.search(r'-p\d+\.html', href):
            # Nettoyer les paramètres d'URL pour garder l'URL canonique
            clean = re.sub(r'\?.*$', '', href)
            urls.add(clean)

    return list(urls)

# Test sur femme
urls_femme = get_product_urls(driver, URLS_LISTES["femme"])
print(f"Femme : {len(urls_femme)} URLs trouvées")
urls_femme[:3]

Femme : 33 URLs trouvées

['https://www.zara.com/fr/fr/robe-midi-fluide-p04772370.html',
 'https://www.zara.com/fr/fr/sandales-a-brides-et-decor-metallique-p12627710.html',
 'https://www.zara.com/fr/fr/pull-asymetrique-en-maille-p09598016.html']

## 5. Fonction de scraping d'un produit

In [8]:
def scrape_produit(driver, url, pause=6):
    """
    Scrape les informations d'une page produit Zara.
    
    Retourne un dict avec :
      nom, url, categorie, couleur, matiere, pays, prix, promo, reference
    """
    try:
        driver.get(url)
        time.sleep(pause)
        html = driver.page_source
    except WebDriverException as e:
        print(f"  [ERREUR WebDriver] {url} : {e}")
        return None
    soup = BeautifulSoup(html, "html.parser")

    # ── NOM ────────────────────────────────────────────────────────────────
    match = re.search(r'"name":"([^"]{3,100})"', html)
    nom = match.group(1) if match else None

    # ── COULEUR ───────────────────────────────────────────────────────────

    color_tag = soup.select_one(
        '[data-qa-qualifier="product-detail-info-color"]'
    )

    if color_tag:
        button = color_tag.find("button")
        if button:
            button.extract()

        couleur = color_tag.get_text(" ", strip=True).strip('"').strip()
    else:
        couleur = None

    # ── MATIÈRE PRINCIPALE ────────────────────────────────────────────────
    match = re.search(
        r'"material":"([^"]+)","percentage":"?([0-9]+)',
        html,
        flags=re.IGNORECASE
    )
    if match:
        matiere_principale = f"{match.group(2)}% {match.group(1)}"
    else:
        matiere_principale = None

    # ── PRIX ──────────────────────────────────────────────────────────────
    price_tag = soup.select_one(".money-amount__main")
    if price_tag:
        prix = price_tag.get_text(" ", strip=True)
    else:
        prix = None

    return {
        "nom":        nom,
        "url":        url,
        "couleur":    couleur,
        "matiere":    matiere_principale,
        "prix":       prix,
    }

In [33]:
# ── TEST sur une URL ─────────────────────────────────────────────────────
if urls_femme:
    test = scrape_produit(driver, urls_femme[0])
    print(test)

{'nom': 'JUPE ASYMÉTRIQUE FLUIDE', 'url': 'https://www.zara.com/fr/fr/jupe-asymetrique-fluide-p01165021.html', 'couleur': 'Sable |', 'matiere': '76% polyester', 'prix': '29,95 EUR'}

## 6. Scraping complet — toutes collections

In [9]:
def scrape_collection(driver, listing_url, pause=3, max=100):
    """
    Récupère toutes les URLs d'une page liste puis scrape chaque produit.
    max_produits : limite le nombre de produits (None = tous).
    """
    urls = get_product_urls(driver, listing_url)
    print(f"  {len(urls)} URLs trouvées")
    urls = urls[:max]

    rows = []
    for i, url in enumerate(urls, 1):
        print(f"  [{i}/{len(urls)}] {url}")
        row = scrape_produit(driver, url,pause=pause)
        if row:
            rows.append(row)

    df = pd.DataFrame(rows, columns=VARIABLES)
    print(f"  → {len(df)} produits récupérés")
    return df

In [10]:
# ── FEMME ────────────────────────────────────────────────────────────────
# max_produits=20 pour un test rapide ; mettre None pour tout scraper
df_femme = scrape_collection(driver, URLS_LISTES["femme"],max=None)
df_femme.head()

  33 URLs trouvées
  [1/33] https://www.zara.com/fr/fr/robe-midi-fluide-p04772370.html
  [2/33] https://www.zara.com/fr/fr/sandales-a-brides-et-decor-metallique-p12627710.html
  [3/33] https://www.zara.com/fr/fr/pull-asymetrique-en-maille-p09598016.html
  [4/33] https://www.zara.com/fr/fr/combinaison-courte-en-lyocell-p06929485.html
  [5/33] https://www.zara.com/fr/fr/jean-trf-loose-folded-taille-basse-a-rayures-p08727114.html
  [6/33] https://www.zara.com/fr/fr/robe-fluide-a-encolure-americaine-p02180312.html
  [7/33] https://www.zara.com/fr/fr/veste-croisee-p04387204.html
  [8/33] https://www.zara.com/fr/fr/lot-de-3-bracelets-bois-et-resine-p07243005.html
  [9/33] https://www.zara.com/fr/fr/sandales-a-talons-imprimees-p13808810.html
  [10/33] https://www.zara.com/fr/fr/short-fluide-a-boutons-p06929421.html
  [11/33] https://www.zara.com/fr/fr/t-shirt-texte-brillant-effet-delave-p06050078.html
  [12/33] https://www.zara.com/fr/fr/veste-a-rayures-100-lin-p02775647.html
  [13/33] https://www.zara.com/fr/fr/pantalon-droit-a-rayures-p02768116.html
  [14/33] https://www.zara.com/fr/fr/chemise-cintree-froncee-p04661097.html
  [15/33] https://www.zara.com/fr/fr/chemise-fluide-a-manches-courtes-p02906210.html
  [16/33] https://www.zara.com/fr/fr/veste-cintree-a-brandebourgs-p04341764.html
  [17/33] https://www.zara.com/fr/fr/top-a-boutons-et-lin-p04174341.html
  [18/33] https://www.zara.com/fr/fr/top-georgette-a-encolure-americaine-p04661038.html
  [19/33] https://www.zara.com/fr/fr/top-fluide-col-en-v-p01165004.html
  [20/33] https://www.zara.com/fr/fr/chemise-oversize-en-coton-p04387052.html
  [21/33] https://www.zara.com/fr/fr/robe-courte-halter-fluide-p06929386.html
  [22/33] https://www.zara.com/fr/fr/short-en-denim-trf-dechire-taille-moyenne-p05252006.html
  [23/33] https://www.zara.com/fr/fr/jupe-asymetrique-fluide-p01165021.html
  [24/33] https://www.zara.com/fr/fr/short-mini-denim-trf-etoiles-p06929004.html
  [25/33] https://www.zara.com/fr/fr/chemise-fluide-a-manches-courtes-p06929068.html
  [26/33] https://www.zara.com/fr/fr/pantalon-a-rayures-100-lin-p02444647.html
  [27/33] https://www.zara.com/fr/fr/bonnet-lisse-calot-p00653020.html
  [28/33] https://www.zara.com/fr/fr/short-evase-en-satin-p01255472.html
  [29/33] https://www.zara.com/fr/fr/pantalon-fluide-large-p04387104.html
  [30/33] https://www.zara.com/fr/fr/pantalon-fluide-a-cordons-p06929019.html
  [31/33] https://www.zara.com/fr/fr/sandales-plates-en-daim-a-boucle-p13646710.html
  [32/33] https://www.zara.com/fr/fr/bonnet-calot-tresse-p01023203.html
  [33/33] https://www.zara.com/fr/fr/robe-courte-en-maille-a-rayures-p06771038.html
  → 33 produits récupérés

,nom,url,couleur,matiere,prix
0,ROBE MI-LONGUE FLUIDE,https://www.zara.com/fr/fr/robe-midi-fluide-p0...,Mauve poudré |,88% viscose,"25,99 EUR"
1,SANDALES À BRIDES ET DÉCOR MÉTALLIQUE,https://www.zara.com/fr/fr/sandales-a-brides-e...,Marron |,100% polyuréthane,"39,95 EUR"
2,PNG,https://www.zara.com/fr/fr/pull-asymetrique-en...,None,None,"25,95 EUR"
3,COMBI-SHORT LYOCELL,https://www.zara.com/fr/fr/combinaison-courte-...,Noir |,100% lyocell,"35,95 EUR"
4,JEAN TRF LOOSE FOLDED TAILLE BASSE À RAYURES,https://www.zara.com/fr/fr/jean-trf-loose-fold...,unique |,100% coton,"35,95 EUR"

In [12]:
# ── HOMME ────────────────────────────────────────────────────────────────
df_homme = scrape_collection(driver, URLS_LISTES["homme"])
df_homme.head()

  118 URLs trouvées
  [1/100] https://www.zara.com/fr/fr/lunettes-de-soleil-rectangulaires-p02750301.html
  [2/100] https://www.zara.com/fr/fr/blazer-regular-fit-en-daim-p02521169.html
  [3/100] https://www.zara.com/fr/fr/sac-shopper-en-tissu-p13352720.html
  [4/100] https://www.zara.com/fr/fr/t-shirt-imprime-contraste-a-piece-p06224203.html
  [5/100] https://www.zara.com/fr/fr/pantalon-plisse-de-costume-100-lin-p04504783.html
  [6/100] https://www.zara.com/fr/fr/lunettes-de-soleil--il-de-chat-p02727301.html
  [7/100] https://www.zara.com/fr/fr/lunettes-de-soleil-rectangulaires-p02750300.html
  [8/100] https://www.zara.com/fr/fr/blouson-technique-relaxed-fit-p01437441.html
  [9/100] https://www.zara.com/fr/fr/chemise-a-carreaux-broderie-contraste-p07446424.html
  [10/100] https://www.zara.com/fr/fr/jorts-en-denim-a-ceinture-p01416477.html
  [11/100] https://www.zara.com/fr/fr/mocassins-en-cuir-avec-masque-p12678720.html
  [12/100] https://www.zara.com/fr/fr/sac-bandouliere-en-cuir-p13622720.html
  [13/100] https://www.zara.com/fr/fr/polo-technique-a-zip-p06861692.html
  [14/100] https://www.zara.com/fr/fr/sac-bandouliere-unie-p13623720.html
  [15/100] https://www.zara.com/fr/fr/espadrille-en-cuir-p12760720.html
  [16/100] https://www.zara.com/fr/fr/sweat-pique-col-zippe-p04092342.html
  [17/100] https://www.zara.com/fr/fr/bandana-a-imprime-geometrique-graphique-p03921414.html
  [18/100] https://www.zara.com/fr/fr/chemise-fluide-a-imprime-fleuri-p04138217.html
  [19/100] https://www.zara.com/fr/fr/chemise-smoking-a-poignets-mousquetaires-p04619270.html
  [20/100] https://www.zara.com/fr/fr/pantalon-relaxed-straight-fit-a-rayures-p04575407.html
  [21/100] https://www.zara.com/fr/fr/veste-en-denim-avec-brandenbourgs-et-boutons-p06688420.html
  [22/100] https://www.zara.com/fr/fr/blouson-d%C3%A9lav%C3%A9-coupe-relax-p04575402.html
  [23/100] https://www.zara.com/fr/fr/chemise-a-carreaux-lin-et-coton-p05588847.html
  [24/100] https://www.zara.com/fr/fr/veste-croisee-costume-chevron-100-lin-p04743764.html
  [25/100] https://www.zara.com/fr/fr/online-exclusive---zara-hair-cire-coiffante-p21110080.html
  [26/100] https://www.zara.com/fr/fr/bermuda-fluide-douce-a-plis-p04242302.html
  [27/100] https://www.zara.com/fr/fr/lunettes-de-soleil-ovales-p02727302.html
  [28/100] https://www.zara.com/fr/fr/chemise-en-maille-regular-fit-p06674437.html
  [29/100] https://www.zara.com/fr/fr/blazer-relaxed-fit-costume-100-lin-p04503783.html
  [30/100] https://www.zara.com/fr/fr/pantalon-regular-fit-de-smoking-a-bandes-p04617350.html
  [31/100] https://www.zara.com/fr/fr/lunettes-de-soleil-rectangulaires-p02750302.html
  [32/100] https://www.zara.com/fr/fr/ceinture-en-cuir-effet-vintage-p05919405.html
  [33/100] https://www.zara.com/fr/fr/pantalon-chino-straight-fit-delave-p01063423.html
  [34/100] https://www.zara.com/fr/fr/polo-structure-en-pique-p00526446.html
  [35/100] https://www.zara.com/fr/fr/pantalon-coupe-decontractee-a-plis-p05862111.html
  [36/100] https://www.zara.com/fr/fr/t-shirt-jacquard-a-rayures-p00526304.html
  [37/100] https://www.zara.com/fr/fr/chemise-relaxed-fit-100-lin-poches-plis-p01195385.html
  [38/100] https://www.zara.com/fr/fr/chemise-col-smoking-p04618270.html
  [39/100] https://www.zara.com/fr/fr/veste-a-rayures-100%C2%A0-lin-p03077878.html
  [40/100] https://www.zara.com/fr/fr/chemise-regular-fit-100-lin-p04610303.html
  [41/100] https://www.zara.com/fr/fr/online-exclusive---zara-hair-gel-fixation-extra-forte-p21110079.html
  [42/100] https://www.zara.com/fr/fr/chemise-a-rayures-et-imprime-citrons-p01195480.html
  [43/100] https://www.zara.com/fr/fr/pantalon-coupe-decontractee-viscose-chanvre-p04673742.html
  [44/100] https://www.zara.com/fr/fr/lunettes-de-soleil-ovales-p02907411.html
  [45/100] https://www.zara.com/fr/fr/polo-pique-regular-fit-p00526302.html
  [46/100] https://www.zara.com/fr/fr/sandales-a-brides-aaron-levine-x-zara-p12796720.html
  [47/100] https://www.zara.com/fr/fr/pantalon-relaxed-fit-viscose---lin-ceinture-p04391451.html
  [48/100] https://www.zara.com/fr/fr/chemise-relaxed-fit-a-imprime-geometrique-p04136216.html
  [49/100] https://www.zara.com/fr/fr/chemise-relaxed-fit-viscose---chanvre-p04670742.html
  [50/100] https://www.zara.com/fr/fr/surchemise-a-pieces-etoiles-p07446455.html
  [51/100] https://www.zara.com/fr/fr/chemise-regular-fit-100-lin-p04611303.html
  [52/100] https://www.zara.com/fr/fr/pantalon-regular-fit-viscose---coton-p06861002.html
  [53/100] https://www.zara.com/fr/fr/chaussettes-cannelees-p03992489.html
  [54/100] https://www.zara.com/fr/fr/debardeur-en-maille-imprime-delave-p04805447.html
  [55/100] https://www.zara.com/fr/fr/t-shirt-regular-fit-jacquard-a-rayures-p00526311.html
  [56/100] https://www.zara.com/fr/fr/veste-de-smoking-a-revers-chale-p04616350.html
  [57/100] https://www.zara.com/fr/fr/pantalon-relaxed-fit-viscose-lin-ceinture-p04391452.html
  [58/100] https://www.zara.com/fr/fr/lunettes-de-soleil-metalliques-carrees-p02907302.html
  [59/100] https://www.zara.com/fr/fr/chemise-%C3%A0-carreaux-lin-et-coton-p05588847.html
  [60/100] https://www.zara.com/fr/fr/bermuda-regular-fit-plis-p06786007.html
  [61/100] https://www.zara.com/fr/fr/ceinture-en-soie-pour-smoking-p09569426.html
  [62/100] https://www.zara.com/fr/fr/pantalon-regular-fit-plis-smoking-p04415978.html
  [63/100] https://www.zara.com/fr/fr/chemise-relaxed-fit-a-pieces-et-texte-p05644433.html
  [64/100] https://www.zara.com/fr/fr/lunettes-de-soleil-m%C3%A9talliques-ovales-p02907300.html
  [65/100] https://www.zara.com/fr/fr/online-exclusive---zara-hair-cire-en-stick-p21110081.html
  [66/100] https://www.zara.com/fr/fr/chemise-relaxed-fit-imprime-patchwork-p04139217.html
  [67/100] https://www.zara.com/fr/fr/bermuda-denim-relaxed-fit-a-plis-p03991478.html
  [68/100] https://www.zara.com/fr/fr/blouson-delave-coupe-relax-p04575402.html
  [69/100] https://www.zara.com/fr/fr/sandales-style-pecheur-en-cuir-p12465720.html
  [70/100] https://www.zara.com/fr/fr/t-shirt-relaxed-fit-graphique-a-carreaux-p06224867.html
  [71/100] https://www.zara.com/fr/fr/bandana-a-imprime-paisley-p03920465.html
  [72/100] https://www.zara.com/fr/fr/chemise-fluide-soft-p04241302.html
  [73/100] https://www.zara.com/fr/fr/chemise-regular-fit-100%C2%A0-lin-p00706333.html
  [74/100] https://www.zara.com/fr/fr/pantalon-regular-fit-100-lin-p04612303.html
  [75/100] https://www.zara.com/fr/fr/sac-bandouliere-en-cuir-p13603720.html
  [76/100] https://www.zara.com/fr/fr/surchemise-relaxed-fit-a-fermeture-eclair-p07446414.html
  [77/100] https://www.zara.com/fr/fr/online-exclusive---zara-hair-poudre-texturisante-mate-p21116001.html
  [78/100] https://www.zara.com/fr/fr/short-coupe-baggy-a-boutons-p07147431.html
  [79/100] https://www.zara.com/fr/fr/jean-droit-contraste-p05585406.html
  [80/100] https://www.zara.com/fr/fr/collier-fantaisie-pierre-p05502422.html
  [81/100] https://www.zara.com/fr/fr/espadrille-en-tricot-p12740720.html
  [82/100] https://www.zara.com/fr/fr/pantalon-de-costume-chevrons-100-lin-p06229764.html
  [83/100] https://www.zara.com/fr/fr/sac-shopper-tress%C3%A9-p13350720.html
  [84/100] https://www.zara.com/fr/fr/blouson-en-jean-a-fermeture-eclair-p03991489.html
  [85/100] https://www.zara.com/fr/fr/ceinture-en-cuir-tresse-p02823406.html
  [86/100] https://www.zara.com/fr/fr/pantalon-cargo-parachute-delave-p03918403.html
  [87/100] https://www.zara.com/fr/fr/sabots-en-cuir-p12770620.html
  [88/100] https://www.zara.com/fr/fr/basket-style-retro-p12345720.html
  [89/100] https://www.zara.com/fr/fr/lunettes-de-soleil-%C5%93il-de-chat-p02727301.html
  [90/100] https://www.zara.com/fr/fr/t-shirt-relaxed-fit-a-imprime-graphique-p04805458.html
  [91/100] https://www.zara.com/fr/fr/frisbee-graphique-imprime-p06452400.html
  [92/100] https://www.zara.com/fr/fr/chapeau-bob-a-bord-large-p04988408.html
  [93/100] https://www.zara.com/fr/fr/ceinture-en-cuir-surpiquee-p06399402.html
  [94/100] https://www.zara.com/fr/fr/veste-regular-fit-a-poches-p06786078.html
  [95/100] https://www.zara.com/fr/fr/mocassins-en-cuir-a-masque-p12662720.html
  [96/100] https://www.zara.com/fr/fr/sandales-en-cuir-%C3%A0-double-bride-p12738720.html
  [97/100] https://www.zara.com/fr/fr/pull-regular-fit-100-lin-p02893445.html
  [98/100] https://www.zara.com/fr/fr/chemise-fluide-a-n-ud-p05588450.html
  [99/100] https://www.zara.com/fr/fr/t-shirt-en-maille-lavee-imprimes-p04805470.html
  [100/100] https://www.zara.com/fr/fr/chemise-structuree-oxford-p03277400.html
  → 100 produits récupérés

,nom,url,couleur,matiere,prix
0,LUNETTES DE SOLEIL RECTANGULAIRES,https://www.zara.com/fr/fr/lunettes-de-soleil-...,Rouge foncé |,100% acétate,"59,95 EUR"
1,BLAZER REGULAR FIT EN DAIM,https://www.zara.com/fr/fr/blazer-regular-fit-...,Sable |,100% cuir de chèvre,"199,00 EUR"
2,SAC SHOPPER EN TISSU,https://www.zara.com/fr/fr/sac-shopper-en-tiss...,Blanc écru |,100% coton,"29,95 EUR"
3,T-SHIRT IMPRIMÉ CONTRASTANT AVEC PIÈCE,https://www.zara.com/fr/fr/t-shirt-imprime-con...,Bleu ciel |,100% coton,"22,95 EUR"
4,PANTALON À PLIS DE COSTUME 100 % LIN,https://www.zara.com/fr/fr/pantalon-plisse-de-...,Blanc |,100% lin,"59,95 EUR"

In [13]:
# ── ENFANTS ──────────────────────────────────────────────────────────────
df_fille = scrape_collection(driver, URLS_LISTES["fille"])
df_fille.head()

  147 URLs trouvées
  [1/100] https://www.zara.com/fr/fr/6-14-ans--bikini-brillant-p01492640.html
  [2/100] https://www.zara.com/fr/fr/ensemble-t-shirt-et-bermuda-a-rayures-p09144607.html
  [3/100] https://www.zara.com/fr/fr/ballerines-sport-barefoot-p12331730.html
  [4/100] https://www.zara.com/fr/fr/pantalon-wide-leg-en-molleton-penn---p09000002.html
  [5/100] https://www.zara.com/fr/fr/short-a-rayures-penn---p06345850.html
  [6/100] https://www.zara.com/fr/fr/top-halter-fantaisie-p03641601.html
  [7/100] https://www.zara.com/fr/fr/lot-de-deux-colliers-avec-fantasie-et-coquillages-p07243585.html
  [8/100] https://www.zara.com/fr/fr/jupe-a-plis-plats-penn---p05987619.html
  [9/100] https://www.zara.com/fr/fr/top-polo-a-rayures-penn---p05987618.html
  [10/100] https://www.zara.com/fr/fr/baskets-de-sport-combinees-p14330730.html
  [11/100] https://www.zara.com/fr/fr/polo-brode-penn---p05871704.html
  [12/100] https://www.zara.com/fr/fr/2-6-ans--maillot-de-bain-fleur-hibiscus-p05644438.html
  [13/100] https://www.zara.com/fr/fr/sandales-de-bain-c-ur-p12701830.html
  [14/100] https://www.zara.com/fr/fr/salopette-courte-a-rayures-penn---p04551647.html
  [15/100] https://www.zara.com/fr/fr/sweat-penn---p05871674.html
  [16/100] https://www.zara.com/fr/fr/blouson-leger-deperlant-penn---p05644954.html
  [17/100] https://www.zara.com/fr/fr/bermuda-effet-serviette-penn---p09000004.html
  [18/100] https://www.zara.com/fr/fr/tennis-en-cuir-p14438730.html
  [19/100] https://www.zara.com/fr/fr/maillot-de-bain-a-rayures-6-14-ans-p04354632.html
  [20/100] https://www.zara.com/fr/fr/pantalon-large-schiffly-p04786780.html
  [21/100] https://www.zara.com/fr/fr/top-polo-a-motifs-torsades-penn---p02756622.html
  [22/100] https://www.zara.com/fr/fr/pareo-hibiscus-et-fantaisies-p01821649.html
  [23/100] https://www.zara.com/fr/fr/porte-cles-pendentif-penn---p03366651.html
  [24/100] https://www.zara.com/fr/fr/lot-de-cinq-chaussettes-hautes-a-rayures-p06068564.html
  [25/100] https://www.zara.com/fr/fr/t-shirt-epais-rayures-p00962612.html
  [26/100] https://www.zara.com/fr/fr/sac-bowling-penn---p11477730.html
  [27/100] https://www.zara.com/fr/fr/tennis-ou-basket-a-semelle-epaisse-p14402730.html
  [28/100] https://www.zara.com/fr/fr/ensemble-t-shirt-a-lacets-et-pantalon-jogger-p00613602.html
  [29/100] https://www.zara.com/fr/fr/basket-ouverte-p12326730.html
  [30/100] https://www.zara.com/fr/fr/sandales-en-cuir-p12649730.html
  [31/100] https://www.zara.com/fr/fr/lot-de-trois-chaussettes-hautes-a-rayures-sportives-p04547612.html
  [32/100] https://www.zara.com/fr/fr/t-shirt-stickers-hello-kitty---sanrio-p08675619.html
  [33/100] https://www.zara.com/fr/fr/grande-balle-de-tennis-avec-boite-penn---p03366690.html
  [34/100] https://www.zara.com/fr/fr/lunettes-de-soleil-en-plastique-fin-p00475548.html
  [35/100] https://www.zara.com/fr/fr/gilet-matelasse-p05854604.html
  [36/100] https://www.zara.com/fr/fr/lot-de-trois-pinces-a-rayures-p02326548.html
  [37/100] https://www.zara.com/fr/fr/short-100-lin-p01613028.html
  [38/100] https://www.zara.com/fr/fr/pantalon-imprime-fleurs-avec-lin-p01614066.html
  [39/100] https://www.zara.com/fr/fr/tennis-a-lacets-p14426730.html
  [40/100] https://www.zara.com/fr/fr/t-shirt-jogging-en-molleton-p00039641.html
  [41/100] https://www.zara.com/fr/fr/lot-de-deux-colliers-papillons-p04319553.html
  [42/100] https://www.zara.com/fr/fr/bermuda-penn---p05871691.html
  [43/100] https://www.zara.com/fr/fr/jupe-short-a-volants-et-rayures-p01165611.html
  [44/100] https://www.zara.com/fr/fr/chemise-texturee-a-rayures-penn---p03366605.html
  [45/100] https://www.zara.com/fr/fr/sac-bandouliere-a-fantaisies-p11222730.html
  [46/100] https://www.zara.com/fr/fr/blouson-kangourou-penn---p05854608.html
  [47/100] https://www.zara.com/fr/fr/casquette-broderie-penn---p03366653.html
  [48/100] https://www.zara.com/fr/fr/chapeau-bob-penn---p03366654.html
  [49/100] https://www.zara.com/fr/fr/lot-de-quatre-chouchous-a-rayures-p02326555.html
  [50/100] https://www.zara.com/fr/fr/chapeau-bob-a-texte-brode-p00653591.html
  [51/100] https://www.zara.com/fr/fr/robe-drapee-avec-lin-p01594066.html
  [52/100] https://www.zara.com/fr/fr/short-en-jean-dechire-p04551635.html
  [53/100] https://www.zara.com/fr/fr/sandales-a-brides-p12640730.html
  [54/100] https://www.zara.com/fr/fr/chemise-a-rayures-penn---p02675621.html
  [55/100] https://www.zara.com/fr/fr/ballerines-sport-p12430730.html
  [56/100] https://www.zara.com/fr/fr/6-14-ans--maillot-de-bain-texture-fleurs-3d-p06668628.html
  [57/100] https://www.zara.com/fr/fr/haut-detail-maille-crochet-p05580605.html
  [58/100] https://www.zara.com/fr/fr/legging-court-cotele-p09006650.html
  [59/100] https://www.zara.com/fr/fr/basket-compensee-p12401730.html
  [60/100] https://www.zara.com/fr/fr/top-boule-en-lin-p01578066.html
  [61/100] https://www.zara.com/fr/fr/lot-trois-hauts-a-rayures-p09000612.html
  [62/100] https://www.zara.com/fr/fr/lot-de-trois-pinces-fleurs-d-hibiscus-p04701552.html
  [63/100] https://www.zara.com/fr/fr/pantalon-en-molleton-heavy-jersey-a-jambes-larges-p04424608.html
  [64/100] https://www.zara.com/fr/fr/poncho-de-bain-a-pois-p07096549.html
  [65/100] https://www.zara.com/fr/fr/short-en-jean-a-rayures-p06045615.html
  [66/100] https://www.zara.com/fr/fr/t-shirt-teint-en-piece-imprime-p07950611.html
  [67/100] https://www.zara.com/fr/fr/t-shirt-imprime-penn---p09006657.html
  [68/100] https://www.zara.com/fr/fr/bonnet-bucket-coutures-p00653613.html
  [69/100] https://www.zara.com/fr/fr/casquette-effet-delave-brodee-p01879563.html
  [70/100] https://www.zara.com/fr/fr/polo-brode-penn---p05871660.html
  [71/100] https://www.zara.com/fr/fr/cire-effet-gomme-capuche-deperlant-p05475602.html
  [72/100] https://www.zara.com/fr/fr/6-14-ans-bikini-texture-n-ud-p03391643.html
  [73/100] https://www.zara.com/fr/fr/sac-bandouliere-technique-p11137730.html
  [74/100] https://www.zara.com/fr/fr/bermuda-waffle-a-inscription-p00208608.html
  [75/100] https://www.zara.com/fr/fr/t-shirt-a-rayures-et-manches-raglan-p09006676.html
  [76/100] https://www.zara.com/fr/fr/veste-en-jean-p04551608.html
  [77/100] https://www.zara.com/fr/fr/sandales-techniques-p12638730.html
  [78/100] https://www.zara.com/fr/fr/t-shirt-imprime-penn---p05871707.html
  [79/100] https://www.zara.com/fr/fr/haut-cotele-nageur-p04424616.html
  [80/100] https://www.zara.com/fr/fr/bermuda-100-lin-p01588028.html
  [81/100] https://www.zara.com/fr/fr/sac-a-dos-technique-p11134730.html
  [82/100] https://www.zara.com/fr/fr/gilet-en-nylon-penn---p01165937.html
  [83/100] https://www.zara.com/fr/fr/gilet-en-maille-penn---p05755644.html
  [84/100] https://www.zara.com/fr/fr/pantalon-a-plis-penn---p01465529.html
  [85/100] https://www.zara.com/fr/fr/sweat-zippe-basique-p00935605.html
  [86/100] https://www.zara.com/fr/fr/sweat-a-inscription-penn---p09000001.html
  [87/100] https://www.zara.com/fr/fr/gilet-en-maille-penn---p03284650.html
  [88/100] https://www.zara.com/fr/fr/tennis-ou-basket-avec-detail-c-ur-p12400730.html
  [89/100] https://www.zara.com/fr/fr/lot-de-cinq-socquettes-p04547611.html
  [90/100] https://www.zara.com/fr/fr/lunettes-de-soleil-carrees-en-plastique-p00475695.html
  [91/100] https://www.zara.com/fr/fr/casquette-resille-broderie-florale-p03920379.html
  [92/100] https://www.zara.com/fr/fr/tennis-penn---p14492730.html
  [93/100] https://www.zara.com/fr/fr/tennis-a-rabat-et-pieces-p12432730.html
  [94/100] https://www.zara.com/fr/fr/t-shirt-a-inscription-imprimee-p06224361.html
  [95/100] https://www.zara.com/fr/fr/bermuda-de-jogging-en-molleton-p00039640.html
  [96/100] https://www.zara.com/fr/fr/lot-bandeau-et-bracelet-penn---p03366652.html
  [97/100] https://www.zara.com/fr/fr/ensemble-cotele-delave-t-shirt-nageur-et-bermuda-p00613603.html
  [98/100] https://www.zara.com/fr/fr/short-a-inscription-et-contraste-p02614627.html
  [99/100] https://www.zara.com/fr/fr/bermuda-popeline-a-pinces-penn---p06917851.html
  [100/100] https://www.zara.com/fr/fr/bermuda-en-jean-longue-penn---p06045616.html
  → 100 produits récupérés

,nom,url,couleur,matiere,prix
0,MAILLOT DE BAIN DEUX PIÈCES BRILLANT 6-14 ANS,https://www.zara.com/fr/fr/6-14-ans--bikini-br...,Bleu clair |,76% polyamide,"19,95 EUR"
1,ENSEMBLE T-SHIRT ET BERMUDA À RAYURES,https://www.zara.com/fr/fr/ensemble-t-shirt-et...,Bleu |,62% polyester,"17,95 EUR"
2,BALLERINES SPORT BAREFOOT,https://www.zara.com/fr/fr/ballerines-sport-ba...,Blanc écru |,63% polyester,"35,95 EUR"
3,PANTALON EN MOLLETON WIDE LEG PENN ©,https://www.zara.com/fr/fr/pantalon-wide-leg-e...,Vert / Écru |,100% coton,"22,95 EUR"
4,SHORT À RAYURES PENN ©,https://www.zara.com/fr/fr/short-a-rayures-pen...,Bleu clair |,99% coton,"19,95 EUR"

In [14]:
df_garcon = scrape_collection(driver, URLS_LISTES["garçon"])
df_garcon.head()

  167 URLs trouvées
  [1/100] https://www.zara.com/fr/fr/sweat-uni-teint-en-piece-p00935720.html
  [2/100] https://www.zara.com/fr/fr/casquette-en-resille-minecraft---mojang-ab----p00547547.html
  [3/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-uni-p05644466.html
  [4/100] https://www.zara.com/fr/fr/t-shirt-sport-a-inscription-p08054697.html
  [5/100] https://www.zara.com/fr/fr/pantalon-wide-leg-en-molleton-penn---p09000002.html
  [6/100] https://www.zara.com/fr/fr/short-a-rayures-penn---p06345850.html
  [7/100] https://www.zara.com/fr/fr/sweat-imprime-p05372630.html
  [8/100] https://www.zara.com/fr/fr/ensemble-t-shirt-et-bermuda-uni-teint-en-piece-p05048707.html
  [9/100] https://www.zara.com/fr/fr/jean-relaxed-ballon-p06186601.html
  [10/100] https://www.zara.com/fr/fr/jupe-a-plis-plats-penn---p05987619.html
  [11/100] https://www.zara.com/fr/fr/top-polo-a-rayures-penn---p05987618.html
  [12/100] https://www.zara.com/fr/fr/t-shirt-imprime-chupa-chups---p05431936.html
  [13/100] https://www.zara.com/fr/fr/polo-brode-penn---p05871704.html
  [14/100] https://www.zara.com/fr/fr/baskets-techniques-multipieces-p14396730.html
  [15/100] https://www.zara.com/fr/fr/ensemble-t-shirt-et-bermuda-a-inscription-p06325698.html
  [16/100] https://www.zara.com/fr/fr/short-effet-serviette-color-block-broderies-p04805779.html
  [17/100] https://www.zara.com/fr/fr/t-shirt-one-piece-netflix---p01165948.html
  [18/100] https://www.zara.com/fr/fr/salopette-courte-a-rayures-penn---p04551647.html
  [19/100] https://www.zara.com/fr/fr/bermuda-rustique-a-imprime-rayures-p01971880.html
  [20/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-seersucker-a-rayures-p01473676.html
  [21/100] https://www.zara.com/fr/fr/sweat-penn---p05871674.html
  [22/100] https://www.zara.com/fr/fr/blouson-leger-deperlant-penn---p05644954.html
  [23/100] https://www.zara.com/fr/fr/lunettes-de-soleil-metalliques-style-aviateur-p00009698.html
  [24/100] https://www.zara.com/fr/fr/bermuda-effet-serviette-penn---p09000004.html
  [25/100] https://www.zara.com/fr/fr/jean-droit-p04302600.html
  [26/100] https://www.zara.com/fr/fr/top-polo-a-motifs-torsades-penn---p02756622.html
  [27/100] https://www.zara.com/fr/fr/casquette-a-piece-et-resille-p03920370.html
  [28/100] https://www.zara.com/fr/fr/lot-de-cinq-chaussettes-hautes-a-rayures-p06068564.html
  [29/100] https://www.zara.com/fr/fr/porte-cles-pendentif-penn---p03366651.html
  [30/100] https://www.zara.com/fr/fr/short-baggy-etiquette-p07147610.html
  [31/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-broderies-marines-p01473691.html
  [32/100] https://www.zara.com/fr/fr/sac-bowling-penn---p11477730.html
  [33/100] https://www.zara.com/fr/fr/t-shirt-one-piece-netflix---p01165930.html
  [34/100] https://www.zara.com/fr/fr/collier-fantaisie-et-coquillage-p07243591.html
  [35/100] https://www.zara.com/fr/fr/portefeuille-technique-p11482730.html
  [36/100] https://www.zara.com/fr/fr/surchemise-a-losanges-en-crochet-p05536671.html
  [37/100] https://www.zara.com/fr/fr/ensemble-t-shirt-et-bermuda-interlock-p03854738.html
  [38/100] https://www.zara.com/fr/fr/sweat-a-manches-courtes-inscription-en-relief-p01880667.html
  [39/100] https://www.zara.com/fr/fr/t-shirt-rayures-heavy-weight-inscription-p01716670.html
  [40/100] https://www.zara.com/fr/fr/jean-baggy-structure-p06917770.html
  [41/100] https://www.zara.com/fr/fr/t-shirt-imprime-hamacs-p05372762.html
  [42/100] https://www.zara.com/fr/fr/t-shirt-uni-sans-manches-p01716675.html
  [43/100] https://www.zara.com/fr/fr/deguisement-kpop-demon-hunters--netflix---p00653594.html
  [44/100] https://www.zara.com/fr/fr/casquette-logo-brode-p01879567.html
  [45/100] https://www.zara.com/fr/fr/lot-de-trois-chaussettes-hautes-a-rayures-sportives-p04547612.html
  [46/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-double-bas-contraste-p05644291.html
  [47/100] https://www.zara.com/fr/fr/gants-deguisement-kpop-demon-hunters--netflix---p00653586.html
  [48/100] https://www.zara.com/fr/fr/grande-balle-de-tennis-avec-boite-penn---p03366690.html
  [49/100] https://www.zara.com/fr/fr/lunettes-de-soleil-en-plastique-fin-p00475548.html
  [50/100] https://www.zara.com/fr/fr/t-shirt-teint-en-piece-p03443660.html
  [51/100] https://www.zara.com/fr/fr/blouson-leger-deperlant-p05992767.html
  [52/100] https://www.zara.com/fr/fr/gilet-sporty-bimatiere-p01733676.html
  [53/100] https://www.zara.com/fr/fr/cape-deguisement-kpop-demon-hunters--netflix---p00653748.html
  [54/100] https://www.zara.com/fr/fr/tennis-a-lacets-p14426730.html
  [55/100] https://www.zara.com/fr/fr/t-shirt-yoshi-super-mario-bros-----nintendo-p01821671.html
  [56/100] https://www.zara.com/fr/fr/sandales-techniques-p14670730.html
  [57/100] https://www.zara.com/fr/fr/jean-baggy-p04110614.html
  [58/100] https://www.zara.com/fr/fr/bermuda-penn---p05871691.html
  [59/100] https://www.zara.com/fr/fr/lot-de-deux-shorts-unis-p00088704.html
  [60/100] https://www.zara.com/fr/fr/lot-de-trois-socquettes-a-damier-p02496562.html
  [61/100] https://www.zara.com/fr/fr/short-en-molleton-a-etiquette-p00088666.html
  [62/100] https://www.zara.com/fr/fr/bermuda-en-jean-fluide-p01879603.html
  [63/100] https://www.zara.com/fr/fr/tennis-de-sport-barefoot-p14326630.html
  [64/100] https://www.zara.com/fr/fr/short-uni-p01880665.html
  [65/100] https://www.zara.com/fr/fr/chemise-texturee-a-rayures-penn---p03366605.html
  [66/100] https://www.zara.com/fr/fr/baskets-sport-p14302830.html
  [67/100] https://www.zara.com/fr/fr/blouson-kangourou-penn---p05854608.html
  [68/100] https://www.zara.com/fr/fr/casquette-broderie-penn---p03366653.html
  [69/100] https://www.zara.com/fr/fr/sac-banane-technique-p11481730.html
  [70/100] https://www.zara.com/fr/fr/chemise-a-rayures-penn---p02675621.html
  [71/100] https://www.zara.com/fr/fr/bermuda-a-inscription-sport-p08054676.html
  [72/100] https://www.zara.com/fr/fr/t-shirt-heavy-weight-a-inscription-p00722770.html
  [73/100] https://www.zara.com/fr/fr/lot-de-deux-chaussettes-hautes-a-numero-p04547614.html
  [74/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-etiquette-p05644787.html
  [75/100] https://www.zara.com/fr/fr/bermuda-a-inscription-sport-p08054679.html
  [76/100] https://www.zara.com/fr/fr/polo-en-maille-crochet-p03991650.html
  [77/100] https://www.zara.com/fr/fr/t-shirt-imprime-penn---p09006657.html
  [78/100] https://www.zara.com/fr/fr/bonnet-bucket-coutures-p00653613.html
  [79/100] https://www.zara.com/fr/fr/t-shirt-a-rayures-et-inscription-p06208981.html
  [80/100] https://www.zara.com/fr/fr/claquettes-de-bain-p14706730.html
  [81/100] https://www.zara.com/fr/fr/casquette-effet-delave-brodee-p01879563.html
  [82/100] https://www.zara.com/fr/fr/polo-brode-penn---p05871660.html
  [83/100] https://www.zara.com/fr/fr/short-rustique-p03183845.html
  [84/100] https://www.zara.com/fr/fr/sandales-a-brides-croisees-p14662730.html
  [85/100] https://www.zara.com/fr/fr/short-elastiques-en-coton-p09959880.html
  [86/100] https://www.zara.com/fr/fr/t-shirt-sportif-tie---dye-p00962681.html
  [87/100] https://www.zara.com/fr/fr/t-shirt-imprime-penn---p05871707.html
  [88/100] https://www.zara.com/fr/fr/chemise-bowling-imprime-rayures-p00971871.html
  [89/100] https://www.zara.com/fr/fr/t-shirt-uni-p01887772.html
  [90/100] https://www.zara.com/fr/fr/baskets-techniques-p14394730.html
  [91/100] https://www.zara.com/fr/fr/lot-de-quatre-socquettes-unies-p04934599.html
  [92/100] https://www.zara.com/fr/fr/6-14-ans--short-de-bain-stopper-p01473694.html
  [93/100] https://www.zara.com/fr/fr/short-cargo-p09959762.html
  [94/100] https://www.zara.com/fr/fr/gilet-en-nylon-penn---p01165937.html
  [95/100] https://www.zara.com/fr/fr/bermuda-en-molleton-teint-sur-piece-avec-logo-p03443670.html
  [96/100] https://www.zara.com/fr/fr/gilet-en-maille-penn---p05755644.html
  [97/100] https://www.zara.com/fr/fr/pantalon-a-plis-penn---p01465529.html
  [98/100] https://www.zara.com/fr/fr/gilet-en-maille-penn---p03284650.html
  [99/100] https://www.zara.com/fr/fr/sweat-a-inscription-penn---p09000001.html
  [100/100] https://www.zara.com/fr/fr/lot-de-trois-hauts-unis-p01887690.html
  → 100 produits récupérés

,nom,url,couleur,matiere,prix
0,PNG,https://www.zara.com/fr/fr/sweat-uni-teint-en-...,None,None,"15,99 EUR"
1,CASQUETTE RÉSILLE MINECRAFT © MOJANG AB. ™,https://www.zara.com/fr/fr/casquette-en-resill...,Vert |,100% coton,"9,95 EUR"
2,6-14 ANS / SHORT DE BAIN UNI,https://www.zara.com/fr/fr/6-14-ans--short-de-...,Citron vert |,100% polyamide,"16,95 EUR"
3,T-SHIRT SPORT À INSCRIPTION,https://www.zara.com/fr/fr/t-shirt-sport-a-ins...,Mandarine |,52% polyester,"12,95 EUR"
4,PANTALON EN MOLLETON WIDE LEG PENN ©,https://www.zara.com/fr/fr/pantalon-wide-leg-e...,Vert / Écru |,100% coton,"22,95 EUR"

In [15]:
# Fermer le navigateur proprement
driver.quit()
print("Navigateur fermé.")

Navigateur fermé.

In [16]:
df_femme["collection"]="femme"
df_homme["collection"]="homme"
df_fille["collection"]="fille"
df_garcon["collection"]="garçon"

In [17]:
df_total = pd.concat([df_femme, df_homme, df_fille,df_garcon], ignore_index=True)
df_total["categorie"]=df_total["nom"].str.split().str[0]
df_total.head(10)

,nom,url,couleur,matiere,prix,collection,categorie
0,ROBE MI-LONGUE FLUIDE,https://www.zara.com/fr/fr/robe-midi-fluide-p0...,Mauve poudré |,88% viscose,"25,99 EUR",femme,ROBE
1,SANDALES À BRIDES ET DÉCOR MÉTALLIQUE,https://www.zara.com/fr/fr/sandales-a-brides-e...,Marron |,100% polyuréthane,"39,95 EUR",femme,SANDALES
2,PNG,https://www.zara.com/fr/fr/pull-asymetrique-en...,None,None,"25,95 EUR",femme,PNG
3,COMBI-SHORT LYOCELL,https://www.zara.com/fr/fr/combinaison-courte-...,Noir |,100% lyocell,"35,95 EUR",femme,COMBI-SHORT
4,JEAN TRF LOOSE FOLDED TAILLE BASSE À RAYURES,https://www.zara.com/fr/fr/jean-trf-loose-fold...,unique |,100% coton,"35,95 EUR",femme,JEAN
5,ROBE FLUIDE À ENCOLURE AMÉRICAINE,https://www.zara.com/fr/fr/robe-fluide-a-encol...,Vert huile |,86% viscose,"35,95 EUR",femme,ROBE
6,VESTE CROISÉE,https://www.zara.com/fr/fr/veste-croisee-p0438...,brique foncée |,89% viscose,"32,95 EUR",femme,VESTE
7,LOT DE 3 BRACELETS BOIS ET RÉSINE,https://www.zara.com/fr/fr/lot-de-3-bracelets-...,Multicolore |,60% bois de manguier,"19,95 EUR",femme,LOT
8,SANDALES À TALONS IMPRIMÉES,https://www.zara.com/fr/fr/sandales-a-talons-i...,Léopard |,100% polyester,"32,95 EUR",femme,SANDALES
9,SHORT FLUIDE AVEC BOUTONS,https://www.zara.com/fr/fr/short-fluide-a-bout...,Mauve clair |,83% viscose,"22,95 EUR",femme,SHORT

In [18]:
# Export CSV
df_total.to_csv("zara_data.csv", index=False, encoding="utf-8-sig")
print("Fichier 'zara_data.csv' exporté.")

Fichier 'zara_data.csv' exporté.